// src/songs.ts

export type Song = {
  id: string;
  title: string;
  //   artist: string;
  // Use Tailwind gradient classes here
  color: string;
  //   title_color: string;
  lyrics: string[];
};

export const SONG_DATABASE: Song[] = [
  {
    id: "1",
    title: "Nuvvunte Chaley",
    // artist: "",
    color: "from-purple-900 via-indigo-900 to-blue-900",
    // title_color: "from-blue-900 via-indigo-900 to-purple-900",
    lyrics: [
      "Oka Chooputo Naalone Puttinde",
      "Edo Vintaga Gundelo Cherinde",
      "Nuvvavaro Naalo Ani Adigane",
      "Tanega Premani Thelipinde",

      "Parichayam Ledani Adiga Premante",
      "Kalisanga Ikapai Manamega Ande",
      "Vethikina Dorakani Artham Premade",
      "Adi Neekento Oka Matalo Cheppale",

      "Nuvvunte Chaley",
      "Nuvvunte Chaley",
      "Nuvvunte Chaley",

      "Matalatho Cheppamante Cheppalene",
      "Bhaavamedo Bhaashalake Andanande",
      "Ademito Kuduruga Undalene Nuvvunte",
      "Adigite Ademito Ardhankade",

      "Ninna Monna Naalo Unna Nene Kaade",
      "Puttindante Neetho Thappa",
      "Pone Pode Premanthe",

      "Daareleni Oorine Adigaanuga",
      "Nuvvega Daarani Naaku Chooputundi",
      "Kammukunna Mabbulo Vethikaanuga",
      "Are Gaali Vaanai Nannu Thaakutundi",
      "Naake Theliyani Naalo Yuddhama",

      "Lolona Sandhrama",
      "Lede Pongutunnade Inkedo",

      "Peru Leducuga Inthe Maata Raaduga",
      "Anthe Oppukomari Vinthele",

      "Nuvvunte Chale",
      "Matalatho Cheppamante Cheppalene",
      "Bhaavamedo Bhaashalake Andanande",
      "Ademito Kuduruga Undalene Nuvvunte",
      "Adigite Ademito Ardhankade",

      "Ninna Monna Naalo Unna Nene Kaade",
      "Puttindante Neetho Thappa",
      "Pone Pode Premanthe",

      "Oo Oo Oo Oo Nuvvunte Chaley",
      "Oo Oo Oo Oo Nuvvunte Chaley",

      "Nuvvunte Chaley",

      // ... Add full lyrics here
    ],
  },


  
  {
    id: "4",
    title: "Ammayi kitiki pakkana",
    color: "from-purple-900 via-indigo-900 to-blue-900",
    lyrics: [
      "ammayi kitiki pakkana kurchundhi",
      "kitikilonchem kanabaduthundhi",
      "ghantaki debhai milella vegamthoti",
      "ye lokam paregeduthundandi",
      "akkada chudu thadi chettuvundhi",
      "akkulu voopi tata chebuthundhi",
      "jabili yendhuku vente vasthundhi?",
      "ne paina manasu ayi vuntundhi",
      "paiki kindhaki vooge nela yemandhi",
      "nuvvu vu antene vuyalla avuthanandhi",
      "medhakhi vache gali emanukuntundhi",
      "ne vusulu moyyallantundhi",
      "ohohoho",
      "ammayi gummam dhagara nunchundhi",
      "gummamlonche em kanabaduthundhi",
      "ghantaki yenabhai milella vegamthoti",
      "yevevo alochisthundhi",
    ],
  },
  {
    id: "5",
    title: "Oy Oy",
    color: "from-yellow-700 via-orange-800 to-red-900",
    lyrics: [
      "Noota debbai aaru beach",
      "house lo Prema Devatha",
      "Yellow Choodidharu White",
      "Chunny tho Dhoche Naa Yedha",
      "Oy Oy antu Casual ga Pileche Ro",
      "Oy Oy Twenty Saarlu kallo kalise ro",
      "oy oy empty gunde ninda",
      "nileche ro oy o o o o oy..",
      "Love at first sight naalo kalige..",
      "Love at first sight nannu kadhipe..",
      "Love at first sight nake dorike..",
      "Love at first sight nannu korike..",
      "Roopam lo na beautiful, Chethal lona",
      "duty full, Maatal lona Fundamental..",
      "Annitlona Capable,Andarilona",
      "Careful,Anthe Lenee Sentimental",
      "Cinemalo meriseti Paatra",
      "city lo na dorakadhu ra..",
      "Nijangane thagilanu thara",
      "Vizaagu nagarapu chivarana…",
      "Chal Chal Jarige..",
      "Love at first sight Chill Kalige",
      "Love at first sight phal phal perige",
      "Love at first sight paikedhige..",
    ],
  },
  {
    id: "6",
    title: "Karige loga",
    color: "from-fuchsia-900 via-purple-800 to-blue-900",
    lyrics: [
      "Ooooooo Ooooooooooo",
      "Ooooooo Ooooooooooo",
      "Karige loga ee kshanam..",
      "Gadipeyaali jeevitham..",
      "Silagaa migile naa hrudayam Saakshiga..",
      "Kanulaipoye sagaram..",
      "alalai ponge gynapakam..",
      "Kalale jaare kanneere cheragaa..",
      "Gadiche nimisham gaayamai..",
      "Prathi gaayam o gamyamai..",
      "Aa gamyam ni gurthuga niliche na prema..",
      "Karige loga ee kshanam..",
      "Gadipeyaali jeevitham..",
      "Silagaa migile na hrudayam Saakshiga..",
      "Kanulaipoye sagaram..",
      "alalai ponge gynapakam..",
      "Kalale jaare kanneere cheragaa..",
      "Parugulu theesthu alasina",
      "oo nadhini nenu..",
      "Iru theeraallo dheniki cheruva kaanu..",
      "Niduranu daati nadichina oo kala nenu..",
      "Irukannullo dheniki sontham kanu..",
      "Naa preme nestham ayyinda..",
      "Naa sagamedho prashnaga marindaa.. oo",
      "Nedu ee bandhaniki perunda.. ooo",
      "Vunte vidadhese veelunda .. oo",
      "Karige loga ee kshanam..",
      "Gadipeyaali jeevitham..",
      "Silaga migile na hrudayam Saakshiga..",
      "Kanulaipoye sagaram..",
      "alalai ponge gynapakam..",
      "Kalale jaare kanneere cheraga..",
    ],
  },
  {
    id: "7",
    title: "Apudo ipudo",
    color: "from-pink-900 via-rose-800 to-red-900",
    lyrics: [
      ",SING ALONG!!",
      "Apudo ipudo epudo kalagannane cheli",
      "akado ikado ekado mansichhane mari",
      "kalavo alavo valavo na uhala haasini",
      "madilo kalala medile na kalala suhaasini",
      "evaremanuknna naa",
      "manasande nuvvee nenani",
      "Apudo ipudo epudo kalagannane cheli",
      "akado ikado ekado mansichhane mari",
      "teepikanna inka teeyyanaina teene",
      "edani ante ventane nee perani antane",
      "hayikanna entho hayidaina chote",
      "emitante nuvvu velle darani antane",
      "neelala akasam naa neelam yedante",
      "nee vaalu kallallo undani antane",
      "Apudo ipudo epudo kalagannane cheli",
      "akado ikado ekado mansichhane mari",
    ],
  },
  {
    id: "8",
    title: "Mix",
    color: "from-emerald-900 via-teal-800 to-cyan-900",
    lyrics: [
      ",SING ALONG!!",
      "Oh my beautiful girl",
      "Do you really wanna get on the floor",
      "Oh my glittering pearl",
      "Let’s get on, and rock & roll",
      "O charuseela, swapna bala",
      "Yevvanala, prema paatashala",
      "Malle poola, mafia la",
      "Repinave, gunde lona gola…",
      "Ye hot hot hot hot mexican tequila",
      "Chikkinave chinanati fantasy la",
      "O part part piccha cute Indian masala",
      "Ni smile a love symbol aa…",
      "O charuseela, swapna bala",
      "Yevvanala, prema paatashala",
      "Malle poola, mafia la",
      "Repinave, gunde lona gola…",
      "Ye coniyac la, kottagundi kick",
      "Chetiki andene, soku blank check",
      "Mercury mabbuni poolatho chekkithe",
      "Shilpamai marina sundari",
      "Kamudu rasina glamour dictionary",
      "Ni nadum ompuna scenery…",
      "O charuseela, swapna bala",
      "Yevvanala, prema paatashala",
      "Malle poola, mafia la",
      "Repinave, na lona gola…",
      "Jamurathiri jabilamma, jola paadana ila",
      "Jorugalilo jaji komma, jaraneeyake kala",
      "Vayyari valu kallalona",
      "varala vendi poola vaana",
      "Swarala ooyalugu vela",
      "Jamurathiri jabilamma, jola paadana ila",
      "Jorugalilo jaji komma, jaraneeyake kala...",
    ],
  }
  ,
  
  {
    id: "9",
    title: "Kammani",
    color: "from-purple-900 via-indigo-900 to-blue-900",
    lyrics: [
      "kammani ee prema lekhane",
      "rasindi hrudayame",
      "priyatama neevachata kushalama",
      "nenichata kushalame",
      "oohalanni patle kanula thotalo",
      "toli kalala kavitale mata maatalo",
      "oho",
      "kammani ee prema lekhane",
      "rasindi hrudayame",
      "priyatama neevachata kushalama",
      "nenichata kushalame",
      "gundello gayamedo",
      "challanga manipoye",
      "maaya chese",
      "aa maaye premayae....",
      "enta gaayamaina gaani",
      "na menikemigadu",
      "puvvu soki...nee soku kandene",
      "veliki raani verri prema",
      "kanneeti dhara lona",
      "karugu tunnadi.....",
      "naadu shoka mopa leka",
      "nee gundey badha padite",
      "taala nannadi......",
      "manushu leruga leru",
      "maamoolu prema kadu",
      "agni kante swaccha mainadhi",
      "mama kaarame",
      "ee laali paata ga",
      "rasedi hrudaya maa",
      "umadevi ga",
      "shivuni ardha bhagamai",
      "na lona niluvu maa",
      "shubha laali laali jo",
      "laali laali jo",
      "umadevi laali jo",
      "laali laali jo",
      "mama kaarame",
      "ee laali paata ga",
      "rasedi hrudaya maa",
    ],
  },
  {
    id: "10",
    title: "Mix",
    color: "from-yellow-700 via-orange-800 to-red-900",
    lyrics: [
      "Nijanga nenena..ila ne jatha lo unna",
      "idantha preme na..",
      "enno vintalu chustunna.",
      "yedalo evaro cheri anni chestunnara",
      "venake venake untu ne",
      "pai nanne thostunnara..",
      "hare hare hare hare hare rama",
      "mari ila ela vachesindi dheema",
      "entho husharuga unnade lo lona yemma..",
      "hare hare hare hare hare rama",
      "mari ila ela vachesindi dheema",
      "entho usharuga unnade lo lona yemma",
      "nijanga nene na..ila ne jatha lo unna...",
      "ee vayassulo okko kshanam.. okko vasantham",
      "na manassuke prathikshnam ..nuvve prapancham",
      "o samudramai anukshanam ponge santosham..",
      "adugula lona adugulu vestu",
      "nadichina dooram entho unna",
      "alasata raadu gadachina",
      "kaalam enthani nammanu ga..",
      "nijanga nene na..ila ne jatha lo unna…",
      "idantha preme na..enno vintalu chustunna",
      "Adhey Nanne Nanne Chera Vache Chanchala",
      "Amey Letha Pacha Tamalapaku Vannela",
      "Abba Sogasu Telupu Matakooda Palakala",
      "Arey Ippude Ippude Thechi Pettu Chanchala",
      "Adhi Leni Naadu Nippu Segalu Gundelaa",
      "Aa Okkaganu Okate",
      "Naa Gundelona Ninde",
      "Arey Koncham Koncham Taane",
      "Nannu Peelchi Pippi Chese",
      "Adhi Oke Maata Anna",
      "Bhale Misimi Bangaru Moota",
      "Ippudentha Mothukunna",
      "Adhi Marali Radhu Ranna",
      "Aa Okkaganu Okate",
      "Naa Gundelona Ninde",
      "Arey Koncham Koncham Taane",
      "Nannu Peelchi Pippi Chese...",
    ],
  },
  {
    id: "11",
    title: "Monna Kanipinchavu",
    color: "from-fuchsia-900 via-purple-800 to-blue-900",
    lyrics: [
      "Monna kanipinchavu, maimarachi poyanu",
      "Andaalato nannu, thutlu podicheshave",
      "Ennaenni nallaina, nee jaada padaleka",
      "Endendu vetikaanu",
      "Kaalame vrudha aayane",
      "Paruvaala nee vennela",
      "Kanaleni na vedana",
      "Ee podde na taodu vachhe ila",
      "Ooranta chusela oudam jata",
      "Ee podde na taodu vachhey ila",
      "Ooranta chusela oudam jata",
      "Monna kanipinchavu, maimarachi poyanu",
      "Andaalato nannu, thutlu podicheshave",
      "Ennaenni nallaina, nee jaada padaleka",
      "Endendu vetikaanu",
      "Kaalame vrudha aayane",
      "Trasulo ninne petti",
      "Thukaaniki puttadi pedite",
      "Thulaabharam tugedi preyasi ke",
      "Mukham chusi palike vela",
      "Toli prema chusina nenu",
      "Hattukoka potana andagada",
      "o.. needa vole venbadi unta",
      "Thoduga cheli",
      "Poga vole paruguna vastaa",
      "Pakkane cheli",
      "Vedukalu kalalu rendu",
      "Venta o cheli",
      "Monna kanipinchavu, maimarachi poyanu",
      "Andaalato nannu, thutlu podicheshave",
      "Ennaenni nallaina, nee jaada padaleka",
      "Endendu vetikaanu",
      "Kaalame vrudha aayane",
    ],
  },
  {
    id: "12",
    title: "Inthandham",
    color: "from-pink-900 via-rose-800 to-red-900",
    lyrics: [
      "Inthandham Daari Mallindha",
      "Bhoomipaike Cherukunnadhaa",
      "Lekunte Chekki Untaara",
      "Achchu Neela Shilpa Sampadaa",
      "Jagatthu Choodani",
      "Mahatthu Needhele",
      "Nee Navvu Thaaki",
      "Tharinche Thapassila",
      "Nisheedhulanni",
      "Thalonche Thushaaraanivaa",
      "Visukkune Vellaadu Chandamaamaye",
      "Nuvvunte Naa Panentane",
      "Ee Nelake Digenu Koti Taarale",
      "Neekantha Vennelentane",
      "Chilake Koka Katti",
      "Ninne Chuttumutti",
      "Seethaakokalaayena",
      "Ville Ekkupetti",
      "Mello Thaali Katti",
      "Marala Raamudavvana",
      "Andam Nee Inta",
      "Chesthondhaa Oodigame",
      "Yuddham Chaatindhi",
      "Nee Paina Ee Jagame",
      "Dhasohamandhi Naa Prapanchame",
      "Adhantha Nee Dhaye",
      "Visukkune Vellaadu Chandamaamaye",
      "Nuvvunte Naa Panentane",
      "Ee Nelake Digenu Koti Taarale",
      "Neekantha Vennelentane",
    ],
  },
  {
    id: "13",
    title: "Manasu Maree",
    color: "from-emerald-900 via-teal-800 to-cyan-900",
    lyrics: [
      "Manasu maree mathuga thoogipootunnade",
      "emo ee vela..",
      "Vayasu maree vinthaga visthubothunnade",
      "neede ee leela..",
      "Anthaga kavvisthavem gilli",
      "Andhuke bhandhinchey nannalli",
      "kiladi komali..",
      "gulebakavli..",
      "sukhala javali..",
      "vinali kougili..",
      "Manasu maree mathuga thoogipootunnade",
      "emo ee vela..",
      "Vayasu maree vinthaga visthubothunnade",
      "neede ee leela..",
      "Oo adugulo aduguvai ilaa raa natho",
      "nithyam varaanana..",
      "Aa bathukulo bathukunai nivedistha naa",
      "sarvam jahapana..",
      "Poola nava gaali thova hailo-hailesso-oo",
      "Cheraneeva cheyaneeva seva-le-ve-vo oo..",
      "Manasu maree mathuga thoogipootunnade",
      "emo ee vela..",
      "Vayasu maree vinthaga visthubothunnade",
      "neede ee leela..",
    ],
  },
  {
    id: "14",
    title: "Singles Anthem",
    color: "from-indigo-900 via-purple-800 to-fuchsia-900",
    lyrics: [
      "ey High class nunchi",
      "Low Classu Daakaa naa crush le",
      "Vandaallo Unnaarule",
      "Okalluu Set Avvale",
      "ey kissing kosam hugging kosam",
      "Waiting le…",
      "papenake joggingule",
      "Life Anthaa beggingule",
      "Yennaallilaa",
      "ee ontari bathuke naakilaa",
      "Boyfriend Laa",
      "Nanu Maarachadhe Ye Pillaa",
      "Yem chesinaaaaa",
      "naa status single maaralaa",
      "Naa Vaipilaa chudaadhu",
      "Ae Cindrella",
      "Hoy Singley I am Ready to Mingiley",
      "Life ki Leve Ranguley",
      "Nuv Padavaa Paapa…",
      "Hoy Jantale",
      "Naa Kanta Padithe Mentaley",
      "Ollanthaa jealousy Mantale",
      "Challarchey Paapa…",
      "Oh pretty pretty girl..oo nananana",
      "You are so beautiful..oo nananana",
      "Ma ma ma sassy girl ...oo nananana",
      "you make my life beautiful..ful..",
      "Yendhuko Yemo",
      "ontarai Vunnaanila",
      "Yedhuru Padademo Naaaa",
      "Andhaala devatha",
      "Jaali choopenaa",
      "kaalame naapai ilaa",
      "Yemi thalaraatho",
      "naa kharma kaalindhilaa",
      "Ayyayyo Singley",
      "I am Ready to Mingiley",
      "Life ki Leve Ranguley",
      "Nuv Padavaa Paapa…",
      "Hoy Jantale",
      "Naa kanta padithe Mentaly",
      "Ollanthaa jealousy Mantale",
      "Challarchey Paapa…",
    ],
  },
  {
    id: "15",
    title: "Oh Priya Priya",
    color: "from-cyan-900 via-blue-800 to-indigo-900",
    lyrics: [
      "Oh priya priya",
      "o my dear priya ne premalo",
      "manase munigindi evelaaa",
      "telusa neekaina ontari uhalloo",
      "unnavu divilo nuvvele priya",
      "i love you ani palikinadee",
      "ninu taakina kaasainaa",
      "aligina na cheli navvuloo",
      "ne premani chusthunaa",
      "you are my everything",
      "you are my everything",
      "you are my everything",
      "you are my everything",
      "every thing every thing every thing...",
      "Oh priya priya",
      "o my dear priya ne premalo",
      "manase munigindi evelaaa",
      "praayam ninnedo saayam adigindaa...uhuuu",
      "doobhuchulate vayasu aadindaa...oooo",
      "thulintha peere prema anukunte...",
      "na pedavi ninne dachukuntundiii",
      "vidiga ninnudanna nu nekkem kanivannuu",
      "kadile nekalaku praanam nenuuu",
      "heymantavooo.........",
      "heymantavooo.........",
      "i love you ani palikinadee",
      "ninu taakina kaasainaa",
      "aligina na cheli navvuloo",
      "ne premani chusthunaa",
      "you are my everything",
      "you are my everything",
      "you are my everything",
      "you are my everything",
      "every thing every thing every thing...",
    ],
  },
  {
    id: "16",
    title: "Chikiri",
    color: "from-orange-900 via-red-800 to-rose-900",
    lyrics: [
      "Oh Ohh Ohhh La La La La La",
      "Oh Ohh Ohhh La La La La La..",
      "Aa Chandrullo Mukka Jaarindhe Deenakka",
      "Na Ollanta Aadine Taitakka",
      "Deenandalo Lekka Deeneshaalo Tikka",
      "Na Gundello Poththaande Ukka",
      "O Chikiri Chikiri Chikiri",
      "Chikiri Chikiri Chikkiri",
      "Padtha Padtha Padtha",
      "Enuke Enuke Padta",
      "Saruku Saamaanu Soosi",
      "Meesammelesi Aise Keeka",
      "Chikiri Chikiri Gunte Suraketteshaka",
      "Mundu Venuka Eede Gali Pogesindhe Pilla",
      "Chikiri Chikiri",
      "Aa Chandrullo Mukka Jaarindhe Deenakka",
      "Naa Ollanta Aadine Taitakka",
      "Deenandalo Lekka Deeneshaalo Tikka",
      "Naa Gundello Poththaande Ukka",
      "Aa Mukupai Petti Kopam",
      "Tokkaesave Mukkerandam",
      "Chintakula Undhe Paadam",
      "Sirrakule Nadhiche Vaatam",
      "Em Mokkaavo Andalu Ollanta Onkeelu",
      "Nee Matte Taagindha Thatikallu",
      "Koosinthe Sutthe Neelo Vagalu",
      "Raasethaaruga Ekaraalu",
      "Nuvve Nadichina Sotanta Porlu Dandaloo",
      "O Chikiri Chikiri Chikiri",
      "Chikiri Chikiri Chikkiri",
      "Padta Padtaa Padta Enuke Enuke Padta",
      "Aa Chandrullo Mukka Jaarindhe Deenakka",
      "Naa Ollanta Aadine Taitakka",
      "Deenandalo Lekka Deeneshaalo Tikka",
      "Naa Gundello Pottande Ukkaa Oo",
    ],
  },
  {
    id: "17",
    title: "Aa Sitadevi Navvula",
    color: "from-teal-900 via-emerald-800 to-green-900",
    lyrics: [
      "Aa Seetadevi Navvula",
      "Unnave Enti Maatala",
      "Laskhmanude Leni Ramude",
      "Neeku Eedu Jodu Veede",
      "Andala Buttabommala",
      "Acchanga Kanti Papala",
      "Vennallo Aadapilla La",
      "Ninnu Taluchukundi Eede",
      "Chelliyo Challako Premano Anduko",
      "Nootiko Kotiko Varudu Nenu Le",
      "Ninatti Janmalo Punyame Anduko",
      "Kaallane Adduko Vadhuvu Gane Mari Pove",
      "Ee Kshanam Swayamvaram",
      "Ivala Sambaram",
      "Ee Kshanam Swayamvaram",
      "Ivala Sambaram -LyricsRead.comMusic & Audio",
      "Veedukolu Leni Todu",
      "Andi Swagatam",
      "Ee Kshanam Swayamvaram",
      "Ivala Sambaram",
      "Ivaala Ningi Loni Taara",
      "Talukku Mandi Edurugaara",
      "Vayassu Teerikundadara",
      "Haay Haay Haay",
      "Sogassu Panchutunna Dhara",
      "Nee Pallukkuloni Panchadhara",
      "Aa Paina Oorukodu Lera",
      "Haay Haay Haay",
      "Uyaala Oogutunte Vallo",
      "Ekantham Antu Verey Ledu Lera",
      "Kallaara Ninnu Chusukunte",
      "Haay Haay Haay Haay",
      "Ee Kshanam Swayamvaram",
      "Ivala Sambaram",
      "Ee Kshanam Swayamvaram",
      "Ivala Sambaram -LyricsRead.comTV & Video",
      "Veedukolu Leni Todu",
      "Andi Swagatam",
      "Ee Kshanam Swayamvaram",
      "Ivala Sambaram",
    ],
  },
  {
    id: "18",
    title: "Mix",
    color: "from-rose-900 via-pink-800 to-fuchsia-900",
    lyrics: [
      "Chitikelu vinave BABY",
      "Kilakilamanave BABY",
      "Akata yevanane",
      "Ninu choosi kastha",
      "Mathi chedene",
      "Jaalaina choopaleva",
      "Bhinkama bidiyama",
      "O lalana neevalana",
      "Picchi patti",
      "Ila thiruguthunna",
      "Ee neram needhenante",
      "Nindhisthunna nanukuntaava",
      "Hamsaro",
      "Marry me marry me",
      "Hamsaro",
      "Filrt with me",
      "Get hight with me",
      "Hamsaro",
      "Yevaina yendhukaina",
      "Don’t worry",
      "Hamsaro O hamsaro",
      "Hamsaro",
      "Marry me marry me",
      "Hamsaro",
      "Filrt with me",
      "Get hight with me",
      "Hamsaro",
      "Sidhanga nenu unna",
      "Be ready",
      "Hamsaro O hamsaro",
      "Chilipiga choosthavala",
      "Penavesthavela ninne aapedhelaa",
      "Chivariki nuvve ala",
      "Vesthaave vala neetho vegedhelaa",
      "O premaa kannulo vaale roju",
      "Yentho bagunaa ni kala",
      "Konnale andham gaa vuristhondhi",
      "Aapai cheruputhondhila",
      "Kada dhaaka preminche",
      "Dhaaredho polchedhelaa",
    ],
  },
  {
    id: "19",
    title: "Sirivennela",
    color: "from-purple-900 via-indigo-900 to-blue-900",
    lyrics: [
      "Nela Rajuni Ila Ranini",
      "Kalipindi Kadaa Sirivennela",
      "Dhooramaa Dhooramaa Theeramai Cheruma",
      "Nadi Raathirilo Teralu Terachinadhi",
      "Niddhuralo Magatha",
      "Marachi Udayinchinadhaa",
      "Kulukuloluku Cheli Modati Kalaa",
      "Thana Navvulalo Thaluku Thaluku",
      "Thana Chempalalo Chamaku Chamaku",
      "Thana Muvvalalo Jhanaku Jhanaku",
      "Sarikottha Kalaa....",
      "Thera Dhaati Chera Dhaati",
      "Velugu Choosthunna Bhaamani",
      "Sarisaati Edhameeti",
      "Palakaristhunna Shyamuni",
      "Priyamaara Gamanisthu",
      "Pulakaristhondi Yaamini...",
      "Kalabose Oosule, Oo Oo",
      "Virabose Aashalai, Oo Oo",
      "Navaraathiri Poosina Vekuva Rekhalu",
      "Raasinadhee Navalaa",
      "Mounaale Mamathalai, Oo Oo",
      "Madhuraala Kavithalai, Oo Oo",
      "Thudhi Cherani Kaburula",
      "Kathakali Kadhilenu",
      "Repati Kadhalaku Munnudilaa..",
      "Thana Navvulalo Thaluku Thaluku",
      "Thana Chempalalo Chamaku Chamaku",
      "Thana Muvvalalo Jhanaku Jhanaku",
      "Sarikottha Kalaa..",
    ],
  },
  {
    id: "20",
    title: "Nuvvuntey Chaaley",
    color: "from-yellow-700 via-orange-800 to-red-900",
    lyrics: [
      "Oka Chooputo Naalone Puttinde",
      "Yedho Vinthaga Gundelo Cherinde",
      "Nuvvavaro Naalo Ani Adiganey",
      "Thaaneyga Premani Thelipindhae",
      "Parichayam Ledhanee Adiga Premante",
      "Kalisaanga Ikapai Manameyga Andhae",
      "Vethikina Dorakani Ardham Premadhey",
      "Adhi Nikento OkkaMatalo Cheppaleyy",
      "Nuvvunte Chale...",
      "Nuvvu Unte Chale....",
      "Nuvvunte Chaley…",
      "Matalathho Cheppamantae Cheppalene",
      "Bhavamedho Bhaashalake Andanandhae",
      "Adhemito Kuduruga Vundalene Nuvvu untee",
      "Adigiththe Adhemito Ardhankadhey",
      "Ninna Monna Naalo VUnna Nene Kaadhey",
      "Puttindante Neetho Pone Podhay Premanthey",
      "Daharey Leni Oorine Adiganuga",
      "Nuvvega Dharani Naaku Chooputhundhee",
      "Kammukunna Mabbulo Vethikaanuga",
      "Are Gaali Vaanai Nannu Thaakutundi",
      "Naakey Dheliyani Naalo Yuddhama",
      "Lolona Sandhrama LyricsRead",
      "Ledhe Ponguthunnadhe InkedhoO",
      "Peru Ledhugaa Inthe",
      "Maata Raadhuga",
      "Anthe Oppukomari Vintheleee..",
      "Nuvvunte Chale",
      "Maatalatho Cheppamante Cheppalene",
      "Bhaavamedho Bhaashalake Andanande",
      "Adhemito Kudhuruga Undalene Nuvvunteyy",
      "Adigite Adhemito Ardhankade",
      "Ninna Monna Naalo Unna Nene Kaade",
      "Puttindante Neetho Pone Pode Premanthe",
    ],
  },
  {
    id: "21",
    title: "Kanulanu Thaake",
    color: "from-fuchsia-900 via-purple-800 to-blue-900",
    lyrics: [
      "O kanulanu thaake o kala",
      "Choope ninnila",
      "Nanne marchenaa nuvvayela",
      "O manasunu laage maayala",
      "Vese o vala",
      "nee navvule nedilaa",
      "O haayi neelo unna",
      "Neelone vunna",
      "nee preme Ne korukunna",
      "Neelo vunna neetoraai vunna",
      "Ninne ne preminchina",
      "O kanulanu thaake o kala",
      "Oooo..",
      "O innaallu",
      "anandam velluvayene",
      "Emaindo",
      "ee nimisham dooramaayene",
      "Vennelinka chikatayenna",
      "Navvulinka mayamayyena",
      "Badhalinka needalaagaa Natho saagena",
      "Naalo re gindhi oo gayame",
      "Daare choopenaa ee kalame e.... ee..e",
      "Neevee nenaa",
      "Nee mounam nena",
      "Nee oose e gundelonaa",
      "Neetholena aahaa",
      "O kanulanu thaake o kala",
      "Oooo.",
    ],
  },
  {
    id: "22",
    title: "Nenu Nenuga",
    color: "from-pink-900 via-rose-800 to-red-900",
    lyrics: [
      "Nenu nenuga lene ninna monnala",
      "Leni poni oohallo emito ila",
      "Unnapaatuga edho kotta janmala",
      "Ippude ikkade puttinattugaa",
      "Nenu nenuga lene ninna monnala",
      "Leni poni oohallo emito ila",
      "Unnapaatuga edho kotta janmala",
      "Ippude ikkade puttinattugaa",
      "Poola chettu ooginattu",
      "Paala bottu chindhinattu",
      "Allukundhi naa chuttu Oo chirunavvu",
      "Thene pattu reginattu",
      "Veena mettu onikinattu",
      "Jallumandhi gundello yevare nuvvu",
      "Naa manasuni maimarapuna",
      "Munchina aa vaana",
      "Meekevariki kanipinchadhu yemaina..",
      "Oo…o….ho.. ho..ooo",
      "Nenu nenuga lene ninna monnala",
      "Leni poni oohallo emito ila",
      "Unnapaatuga edho kotta janmala",
      "Ippude ikkade puttinattugaa",
    ],
  },
  {
    id: "23",
    title: "My heart is beating",
    color: "from-emerald-900 via-teal-800 to-cyan-900",
    lyrics: [
      "My heart is beating adhola",
      "Thelusukovaa.. adhi",
      "Yennaali waiting anelaa",
      "Tharumuthondi.. madhi",
      "Pedhavipai palakadhe",
      "Manasulo vunna sangathi",
      "Kanulalo vethikithe dhorukuthundhi",
      "Tea spoon ton baruvavuthundhe",
      "Full moon nannu udikisthundhe",
      "Cloud nine kaalla kindhakochindhe",
      "Land mine gundelo pelindhe",
      "My heart is beating adhola",
      "Thelusukovaa.. adhi",
      "Yennaali waiting anelaa",
      "Tharumuthondi.. madhi",
      "Penu thufaanu yedhaina",
      "Merupu dhadi chesindha",
      "Munupuleni maikana",
      "Madhini munchi poyindha",
      "Urikine peragaduga oopiri salapani baramila",
      "Ne unike vunnadhiga naalo niluvella",
      "Talapulalo chorabaduthu gajibiji ga chelaregala",
      "Thalagada tho talabaduthu",
      "Thellarlu ontariga vegaala",
      "Cellphone nee kaburu thesthunte",
      "Stungun moginattu vuntundhe",
      "Crompton fanu gaali visthunte",
      "Cyclone thaki nattu vuntundhe",
      "My heart is beating adhola",
      "Thelusukovaa.. adhi",
      "Yennaali waiting anelaa",
      "Tharumuthondi.. madhi",
    ],
  }




];

// colors
// "from-red-900 via-pink-800 to-purple-900"
// "from-orange-900 via-red-800 to-pink-900"
// "from-amber-900 via-orange-700 to-red-800"
// "from-yellow-800 via-amber-900 to-orange-950"
// Cool & Moody
// typescript
// "from-blue-950 via-indigo-900 to-purple-900"
// "from-cyan-900 via-blue-900 to-indigo-950"
// "from-teal-900 via-cyan-900 to-blue-950"
// "from-slate-900 via-blue-900 to-indigo-900"
// Neon & Electric
// typescript
// "from-fuchsia-900 via-purple-800 to-blue-900"
// "from-pink-900 via-fuchsia-800 to-violet-900"
// "from-violet-900 via-purple-800 to-fuchsia-900"
// "from-purple-950 via-fuchsia-900 to-pink-800"
// Earthy & Deep
// typescript
// "from-stone-900 via-amber-950 to-orange-900"
// "from-neutral-950 via-stone-900 to-zinc-900"
// "from-emerald-950 via-teal-900 to-cyan-950"
// "from-green-950 via-emerald-900 to-teal-900"
// Dramatic Contrasts
// typescript
// "from-rose-950 via-red-900 to-orange-950"
// "from-indigo-950 via-violet-900 to-fuchsia-950"
// "from-lime-900 via-green-900 to-emerald-950"
// "from-sky-950 via-blue-900 to-violet-950"
